# Generated by Django 5.2 on 2025-04-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='tiendaproductos',
            old_name='precio',
            new_name='codigo',
        ),
    ]
